-- AlterTable
ALTER TABLE `Product` ADD COLUMN `CGST` INTEGER NULL,
    ADD COLUMN `SGST` INTEGER NULL,
    ADD COLUMN `hsnSac` INTEGER NULL;

-- AlterTable
ALTER TABLE `User` ADD COLUMN `GSTIN` VARCHAR(191) NULL;
