export const BASE_URL = process.env.REACT_APP_BACKEND_SERVER_URL;
export const USERS_URL = process.env.REACT_APP_BACKEND_SERVER_USERS_URL;
export const CATEGORY_URL = process.env.REACT_APP_BACKEND_SERVER_CATEGORY_URL;
export const PRODUCT_URL = process.env.REACT_APP_BACKEND_SERVER_PRODUCT_URL;
export const UPLOAD_URL = process.env.REACT_APP_BACKEND_SERVER_UPLOAD_URL;
export const ORDERS_URL = process.env.REACT_APP_BACKEND_SERVER_ORDERS_URL;
export const PAYPAL_URL = process.env.REACT_APP_BACKEND_SERVER_PAYPAL_URL;
